# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 03:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/default.png', upload_to='images/%Y/%m', verbose_name='\u8f6e\u64ad\u56fe')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('is_show', models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a')),
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u8f6e\u64ad\u56fe',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='GoodsClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u7c7b\u522b',
                'verbose_name_plural': '\u5546\u54c1\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='GoodsGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/default.png', upload_to='images/%Y/%m', verbose_name='\u5546\u54c1\u56fe\u7247')),
                ('is_primary', models.BooleanField(default=False, verbose_name='\u662f\u5426\u663e\u793a\u5728\u5217\u8868\u9875')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Goods', verbose_name='\u5546\u54c1')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u56fe\u96c6',
                'verbose_name_plural': '\u5546\u54c1\u56fe\u96c6',
            },
        ),
        migrations.CreateModel(
            name='GroupBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5f00\u56e2\u65f6\u95f4')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('goods_classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.GoodsClassify', verbose_name='\u5546\u54c1\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u56e2\u8d2d',
                'verbose_name_plural': '\u56e2\u8d2d',
            },
        ),
        migrations.CreateModel(
            name='GroupBuyGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name=max)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Goods', verbose_name='\u5546\u54c1')),
                ('group_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.GroupBuy', verbose_name='\u56e2\u8d2d')),
            ],
            options={
                'verbose_name': '\u56e2\u8d2d\u5546\u54c1',
                'verbose_name_plural': '\u56e2\u8d2d\u5546\u54c1',
            },
        ),
    ]
